#---------------------------------------------------------------------------
# Include this file in the Makefile.local or Makefile
#---------------------------------------------------------------------------

CC=gcc

#CFLAGS += -fno-strict-aliasing -arch x86_64 -g -fwrapv \
#          -Wall -Wstrict-prototypes

CFLAGS += -DWITH_LIBLC


CFLAGS += -I../liblc/src
EXTRA_SRCS += swif_full_symbol.c

#---------------------------------------------------------------------------
